src/ProduitsBundle/Entity/Fournisseur.php
<?php

namespace ProduitsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Fournisseur
 *
 * @ORM\Table(name="Fournisseur")
 * @ORM\Entity
 */
class Fournisseur
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50, nullable=false)
     */
    private $nom;




    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }







}

src/ProduitsBundle/Entity/Produit.php
<?php

namespace ProduitsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Produit
 *
 * @ORM\Table(name="produit")
 * @ORM\Entity
 */
class Produit
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_produit", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idProduit;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=50, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="reference", type="string", length=255, nullable=false)
     */
    private $reference;

    /**
     * @var string
     *
     * @ORM\Column(name="categorie", type="string", length=50, nullable=false)
     */
    private $categorie;

    /**
     * @var integer
     *
     * @ORM\Column(name="quantite", type="integer", nullable=false)
     */
    private $quantite;

    /**
     * @var integer
     *
     * @ORM\Column(name="prix", type="integer", nullable=false)
     */
    private $prix;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=false)
     */
    private $description;

    /**
     * @var integer
     *
     * @ORM\Column(name="etoile", type="integer", nullable=false)
     */
    private $etoile = '3';
    /**
     * @var ProduitsBundle\Entity\Fournisseur
     * @ORM\ManyToOne(
     *     targetEntity="ProduitsBundle\Entity\Fournisseur",
     *
     * )
     * @ORM\JoinColumn(name="fournisseur_id", referencedColumnName="id")
     */
    private $fournisseur_id;

    /**
     * @return mixed
     */
    public function getFournisseurId()
    {
        return $this->fournisseur_id;
    }

    /**
     * @param mixed $fournisseur_id
     */
    public function setFournisseurId($fournisseur_id)
    {
        $this->fournisseur_id = $fournisseur_id;
    }

    /**
     * @return int
     */
    public function getIdProduit()
    {
        return $this->idProduit;
    }

    /**
     * @param int $idProduit
     */
    public function setIdProduit($idProduit)
    {
        $this->idProduit = $idProduit;
    }

    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getReference()
    {
        return $this->reference;
    }

    /**
     * @param string $reference
     */
    public function setReference($reference)
    {
        $this->reference = $reference;
    }

    /**
     * @return string
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

    /**
     * @param string $categorie
     */
    public function setCategorie($categorie)
    {
        $this->categorie = $categorie;
    }

    /**
     * @return int
     */
    public function getQuantite()
    {
        return $this->quantite;
    }

    /**
     * @param int $quantite
     */
    public function setQuantite($quantite)
    {
        $this->quantite = $quantite;
    }

    /**
     * @return int
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * @param int $prix
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getEtoile()
    {
        return $this->etoile;
    }

    /**
     * @param int $etoile
     */
    public function setEtoile($etoile)
    {
        $this->etoile = $etoile;
    }


}

src/ProduitsBundle/Controller/DefaultController.php
<?php

namespace ProduitsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function indexAction()
    {
        return $this->render('ProduitsBundle:Default:index.html.twig');
    }
}

src/ProduitsBundle/Controller/ProduitsController.php
<?php

namespace ProduitsBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use ProduitsBundle\Entity\Produit;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class ProduitsController extends Controller
{
    public function indexAction()
    {
        return $this->render('ProduitsBundle:Default:produit.html.twig');
    }

    public function listeProduitAction(){
        $em= $this->getDoctrine()->getManager();
        $Produits=$em->getRepository("ProduitsBundle:Produit")->findAll();
        return $this->render('ProduitsBundle:Default:liste_produits.html.twig', array("produits"=>$Produits));

    }
    public function ajoutproduitAction(Request $request)
    {

        $Produit = new Produit();
        $em= $this->getDoctrine()->getManager();
        $fournisseurs = $em->getRepository("ProduitsBundle:Fournisseur")->findAll();
        if ($request->isMethod('POST')) {

            $Produit->setNom($request->get('nom'));
            $Produit->setDescription($request->get('description'));
            $Produit->setReference($request->get('reference'));
            $Produit->setPrix($request->get('prix'));
            $Produit->setCategorie($request->get('categorie'));
            $Produit->setQuantite($request->get('quantite'));
            $Fournisseur = $em->getRepository("ProduitsBundle:Fournisseur")->find($request->get('fournisseur'));
            $Produit->setFournisseurId($Fournisseur);
            $file = $request->files->get('image');
            $fileName = $file->getClientOriginalName();
            $file->move($this->container->getParameter('path_image_produit'),$fileName);
            $Produit->setImage($fileName);


            $em = $this->getDoctrine()->getManager();
            $em->persist($Produit);
            $em->flush();
            return $this->redirectToRoute('produits_listeProduit');


        }
        return $this->render('ProduitsBundle:Default:ajoutproduit.html.twig',array("fournisseurs"=>$fournisseurs));


    }
}

src/ProduitsBundle/Resources/views/Default/ajoutproduit.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}
    <form method="post" novalidate="novalidate" enctype="multipart/form-data">
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="Nom" name="nom" class="form-control" placeholder="Nom" required="required" autofocus="autofocus">
                        <label for="Nom">Nom</label>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="reference" name="reference" class="form-control" placeholder="Reference" required="required">
                        <label for="reference">Reference</label>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="categorie" name="categorie" class="form-control" placeholder="categorie" required="required" autofocus="autofocus">
                        <label for="categorie">Categorie</label>
                    <!--<select></select>-->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="number" id="quantite" name="quantite" class="form-control" value="1" required="required">
                        <label for="quantite">Quantite</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="number" id="prix" name="prix" class="form-control" value="1"  required="required" autofocus="autofocus">
                        <label for="prix">Prix</label>
                        <!--<select></select>-->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input type="text" id="description" name="description" class="form-control" placeholder="description" required="required">
                        <label for="description">Description</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="form-row">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <select id="fournisseur" style="width:100%" class="form-control custom-select" name="fournisseur" data-rule-required="true">
                            {% for f in fournisseurs %}
                                <option value="{{ f.id }}">{{ f.nom }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-label-group">
                        <input id="logo" type="file" name="image" data-buttontext="Choose image" data-buttonname="btn-outline btn-primary" data-iconname="ti-image" data-rule-accept="image/*" class="filestyle">
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block" href="login.html">Ajouter le produit</button>
    </form>


{% endblock %}

src/ProduitsBundle/Resources/views/Default/index.html.twig
dddd

src/ProduitsBundle/Resources/views/Default/liste_produits.html.twig
{% extends 'baseBack.html.twig' %}
{% block content %}

    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-table"></i>
            Data Table Example</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Reference</th>
                        <th>Categorie</th>
                        <th>Quantiite</th>
                        <th>Prix</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Fournisseur</th>
                        <th>Etoiles</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Nom</th>
                        <th>Reference</th>
                        <th>Categorie</th>
                        <th>Quantiite</th>
                        <th>Prix</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Fournisseur</th>
                        <th>Etoiles</th>
                    </tr>
                    </tfoot>
                    <tbody>
                    {% for i in produits %}
                    <tr>
                        <td>{{  i.idProduit }}</td>
                        <td>{{  i.nom }}</td>
                        <td>{{  i.reference }}</td>
                        <td>{{  i.categorie }}</td>
                        <td>{{  i.quantite }}</td>
                        <td>{{  i.prix}}</td>
                        <td>{{  i.image}}</td>
                        <td>{{  i.description }}</td>
                        <td>{{  i.fournisseurId.nom }}</td>
                        <td>{{  i.etoile }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

{% endblock %}